import heroImage from '@/src/assets/images/hero_mountain_housing_1790351060957.jpg';
import cleanupImage from '@/src/assets/images/community_cleanup_event_1790351075830.jpg';
import gardenImage from '@/src/assets/images/neighborhood_garden_park_1790351090650.jpg';
import {
  Announcement,
  AgendaItem,
  WorkProgram,
  FinanceTransaction,
  DocumentationItem,
  CitizenReport,
  RondaSchedule,
  Household,
  IPLPayment,
} from '../types/portal';

/**
 * MOCK / DEMO DATA ONLY
 * 
 * CATATAN PENTING:
 * Seluruh data di bawah ini merupakan data tiruan (dummy/mock data) untuk
 * keperluan demonstrasi antarmuka dan persiapan integrasi sistem portal warga.
 * Tidak ada informasi pribadi warga, nomor telepon riil, rekening bank,
 * atau data faktual yang diikutsertakan.
 */

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: '[Demo] Pemberitahuan Kegiatan Gotong Royong Kebersihan Lingkungan (Contoh)',
    category: 'kerja-bakti',
    date: '2026-09-24',
    author: '[Pengurus Demo] Koordinator Lingkungan',
    content:
      '(Contoh Konten Pengumuman Warga) Seluruh warga dihimbau untuk berpartisipasi dalam kegiatan gotong royong kebersihan lingkungan berkala di area fasilitas bersama. Warga diharapkan membawa perlengkapan kebersihan masing-masing. Informasi jadwal resmi akan diperbarui secara berkala oleh pengurus.',
    isPinned: true,
    tagline: '[Pengumuman Contoh / Data Demo]',
    createdAt: '2026-09-24T08:00:00.000Z',
  },
  {
    id: 'ann-2',
    title: '[Demo] Laporan Simulasi Rekapitulasi Iuran Lingkungan (Contoh)',
    category: 'iuran',
    date: '2026-09-20',
    author: '[Pengurus Demo] Bendahara',
    content:
      '(Contoh Laporan Iuran) Informasi ini merupakan simulasi pencatatan iuran pengelolaan lingkungan untuk keperluan uji coba portal warga. Rekening resmi paguyuban dan rincian besaran iuran aktual akan disosialisasikan secara resmi oleh pengurus.',
    isPinned: true,
    tagline: '[Simulasi Pembukuan / Data Demo]',
    createdAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'ann-3',
    title: '[Demo] Panduan Ketertiban & Pelaporan Tamu Lingkungan (Contoh)',
    category: 'keamanan',
    date: '2026-09-15',
    author: '[Pengurus Demo] Seksi Keamanan',
    content:
      '(Contoh Panduan Lingkungan) Untuk kenyamanan dan ketertiban bersama, tamu atau kendaraan luar yang berkunjung pada malam hari diharapkan melapor di pos keamanan lingkungan. Standar operasional resmi akan disahkan dalam musyawarah warga.',
    isPinned: false,
    tagline: '[Panduan Contoh / Data Demo]',
    createdAt: '2026-09-15T14:30:00.000Z',
  },
  {
    id: 'ann-4',
    title: '[Demo] Pemeliharaan Fasilitas Umum & Area Hijau Lingkungan (Contoh)',
    category: 'kegiatan',
    date: '2026-09-10',
    author: '[Pengurus Demo] Sarana Prasarana',
    content:
      '(Contoh Pemberitahuan) Pemeliharaan penerangan jalan umum dan perawatan area hijau di lingkungan perumahan telah selesai dilakukan sebagai bagian dari kegiatan perawatan rutin fasilitas bersama.',
    isPinned: false,
    tagline: '[Fasilitas Bersama / Data Demo]',
    createdAt: '2026-09-10T10:15:00.000Z',
  },
];

export const INITIAL_AGENDAS: AgendaItem[] = [
  {
    id: 'ag-1',
    title: '[Demo] Gotong Royong Kebersihan Saluran Air (Contoh Kegiatan)',
    date: '2026-09-27',
    time: '07:30 - 10:00 WIB',
    location: 'Area Terbuka Blok H (Contoh Lokasi)',
    category: 'kerja-bakti',
    description:
      '(Contoh Agenda) Gotong royong berkala warga untuk membersihkan saluran air dan merapikan area rumput fasilitas bersama. Jadwal aktual akan disesuaikan dengan pengumuman resmi paguyuban.',
    pic: 'Bpk. Contoh 01',
    status: 'upcoming',
    createdAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'ag-2',
    title: '[Demo] Musyawarah Warga & Pembahasan Evaluasi Lingkungan (Contoh)',
    date: '2026-10-04',
    time: '19:30 - 21:00 WIB',
    location: 'Area Pertemuan Blok H (Contoh Lokasi)',
    category: 'rapat',
    description:
      '(Contoh Agenda) Pertemuan warga untuk membahas program kerja kepengurusan, transparansi kas, dan usulan fasilitas lingkungan bersama.',
    pic: 'Bpk. Contoh 02',
    status: 'upcoming',
    createdAt: '2026-09-21T11:00:00.000Z',
  },
  {
    id: 'ag-3',
    title: '[Demo] Simulasi Pelayanan Kesehatan Lingkungan (Contoh)',
    date: '2026-10-10',
    time: '08:30 - 11:00 WIB',
    location: 'Balai Pertemuan Lingkungan (Contoh Lokasi)',
    category: 'posyandu',
    description:
      '(Contoh Agenda) Layanan pemeriksaan kesehatan berkala bagi warga. Pelaksanaan aktual akan dikoordinasikan bersama tenaga kesehatan terkait.',
    pic: 'Ibu Contoh 01',
    status: 'upcoming',
    createdAt: '2026-09-22T08:30:00.000Z',
  },
  {
    id: 'ag-4',
    title: '[Demo] Jalan Pagi Bersama Warga Lingkungan (Contoh)',
    date: '2026-09-13',
    time: '06:00 - 07:30 WIB',
    location: 'Jalur Kompleks Blok H (Contoh Lokasi)',
    category: 'olahraga',
    description:
      '(Contoh Agenda) Olahraga jalan santai pagi mengelilingi area kompleks untuk mempererat silaturahmi antarwarga.',
    pic: 'Bpk. Contoh 03',
    status: 'completed',
    createdAt: '2026-09-08T06:00:00.000Z',
  },
];

export const INITIAL_WORK_PROGRAMS: WorkProgram[] = [
  {
    id: 'wp-1',
    title: '[Contoh Program 01] Peningkatan Keamanan & Pengawasan Lingkungan',
    term: 'pendek',
    period: 'Tahap 1 (Contoh Periode)',
    description:
      '(Program Contoh) Perencanaan penguatan sistem keamanan mandiri lingkungan perumahan serta penataan pos keamanan.',
    pic: 'Seksi Keamanan [Pengurus Demo]',
    budgetEstimated: 5000000,
    budgetRealized: 2500000,
    progress: 50,
    status: 'berjalan',
    targets: [
      '(Contoh Target 1) Pemetaan kebutuhan sarana keamanan',
      '(Contoh Target 2) Uji coba peralatan di pos jaga',
      '(Contoh Target 3) Sosialisasi prosedur kepada warga',
    ],
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'wp-2',
    title: '[Contoh Program 02] Perawatan Ruang Terbuka Hijau & Taman',
    term: 'pendek',
    period: 'Tahap 1 (Contoh Periode)',
    description:
      '(Program Contoh) Penataan tanaman hias, pemotongan rumput berkala, dan pemeliharaan area hijau bersama.',
    pic: 'Seksi Lingkungan [Pengurus Demo]',
    budgetEstimated: 3000000,
    budgetRealized: 1500000,
    progress: 50,
    status: 'berjalan',
    targets: [
      '(Contoh Target 1) Pembersihan area fasum',
      '(Contoh Target 2) Pengadaan bibit tanaman penghijauan',
      '(Contoh Target 3) Penjadwalan penyiraman rutin',
    ],
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'wp-3',
    title: '[Contoh Program 03] Pemeliharaan Saluran Drainase Lingkungan',
    term: 'menengah',
    period: 'Tahap 2 (Contoh Periode)',
    description:
      '(Program Contoh) Pemeliharaan berkala saluran air dan penyerapan air hujan untuk kenyamanan lingkungan perumahan.',
    pic: 'Seksi Pembangunan [Pengurus Demo]',
    budgetEstimated: 8000000,
    budgetRealized: 0,
    progress: 0,
    status: 'rencana',
    targets: [
      '(Contoh Target 1) Pengecekan kondisi drainase bersama pengurus',
      '(Contoh Target 2) Estimasi kebutuhan material perawatan',
      '(Contoh Target 3) Pelaksanaan kerja bakti terarah',
    ],
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'wp-4',
    title: '[Contoh Program 04] Digitalisasi Layanan Informasi Warga',
    term: 'panjang',
    period: 'Tahap 3 (Contoh Periode)',
    description:
      '(Program Contoh) Pengembangan portal informasi terpadu warga yang siap diintegrasikan dengan backend Cloudflare Workers & D1 Database.',
    pic: 'Tim Pengembang [Demo]',
    budgetEstimated: 0,
    budgetRealized: 0,
    progress: 25,
    status: 'berjalan',
    targets: [
      '(Contoh Target 1) Perancangan antarmuka mobile-first',
      '(Contoh Target 2) Sentralisasi repositori data di dataService.ts',
      '(Contoh Target 3) Persiapan skema D1 dan API Workers',
    ],
    createdAt: '2026-08-01T00:00:00.000Z',
  },
];

/**
 * Saldo Kas Awal Pembukuan Paguyuban (Mock Data)
 * Saldo awal dipisahkan secara konseptual dan tidak dicatat sebagai transaksi pemasukan.
 */
export const INITIAL_OPENING_BALANCE = 5000000;

export const INITIAL_TRANSACTIONS: FinanceTransaction[] = [
  {
    id: 'tx-01',
    date: '2026-09-22',
    type: 'in',
    category: 'iuran-bulanan',
    description: '[Contoh Transaksi] Simulasi Penerimaan Kas Iuran Lingkungan (Data Demo)',
    amount: 3000000,
    receiptNumber: 'DEMO-IN/202609/001',
    payerOrRecipient: 'Warga [Data Simulasi]',
    paymentMethod: 'transfer_bank',
    referenceNo: 'REF-BANK-20260922-01',
    status: 'active',
    notes: 'Pencatatan kas iuran bulanan demonstrasi',
    createdAt: '2026-09-22T09:30:00.000Z',
    createdBy: 'bendahara_demo',
  },
  {
    id: 'tx-02',
    date: '2026-09-20',
    type: 'out',
    category: 'keamanan-satpam',
    description: '[Contoh Transaksi] Simulasi Biaya Operasional Keamanan Lingkungan (Data Demo)',
    amount: 1500000,
    receiptNumber: 'DEMO-OUT/202609/001',
    payerOrRecipient: 'Operasional Keamanan [Simulasi]',
    paymentMethod: 'transfer_bank',
    referenceNo: 'REF-OPS-20260920-01',
    status: 'active',
    notes: 'Honor satpam periode bulan berjalan (simulasi)',
    createdAt: '2026-09-20T10:00:00.000Z',
    createdBy: 'bendahara_demo',
  },
  {
    id: 'tx-03',
    date: '2026-09-18',
    type: 'out',
    category: 'kebersihan-sampah',
    description: '[Contoh Transaksi] Simulasi Retribusi Pengelolaan Sampah Lingkungan (Data Demo)',
    amount: 500000,
    receiptNumber: 'DEMO-OUT/202609/002',
    payerOrRecipient: 'Pengelolaan Sampah [Simulasi]',
    paymentMethod: 'tunai',
    referenceNo: 'KW-SMPH-20260918',
    status: 'active',
    notes: 'Retribusi truk sampah dan armada pengangkut',
    createdAt: '2026-09-18T14:15:00.000Z',
    createdBy: 'bendahara_demo',
  },
  {
    id: 'tx-04',
    date: '2026-09-15',
    type: 'out',
    category: 'penerangan-cctv',
    description: '[Contoh Transaksi] Simulasi Perawatan Lampu Penerangan Jalan Umum (Data Demo)',
    amount: 250000,
    receiptNumber: 'DEMO-OUT/202609/003',
    payerOrRecipient: 'Penyedia Perlengkapan [Simulasi]',
    paymentMethod: 'tunai',
    referenceNo: 'NOTA-PJU-0915',
    status: 'active',
    notes: 'Penggantian lampu LED PJU jalur utama',
    createdAt: '2026-09-15T11:45:00.000Z',
    createdBy: 'bendahara_demo',
  },
  {
    id: 'tx-05',
    date: '2026-09-12',
    type: 'in',
    category: 'donasi',
    description: '[Contoh Transaksi] Simulasi Penerimaan Dana Sosial Kas Lingkungan (Data Demo)',
    amount: 500000,
    receiptNumber: 'DEMO-IN/202609/002',
    payerOrRecipient: 'Donatur Warga [Simulasi]',
    paymentMethod: 'transfer_bank',
    referenceNo: 'TRF-DONASI-0912',
    status: 'active',
    notes: 'Sumbangan sukarela kas sosial lingkungan',
    createdAt: '2026-09-12T16:00:00.000Z',
    createdBy: 'bendahara_demo',
  },
  {
    id: 'tx-06',
    date: '2026-09-08',
    type: 'out',
    category: 'perawatan-fasum',
    description: '[Contoh Transaksi] Simulasi Pemeliharaan Peralatan Taman & Fasum (Data Demo)',
    amount: 150000,
    receiptNumber: 'DEMO-OUT/202609/004',
    payerOrRecipient: 'Pemeliharaan Fasum [Simulasi]',
    paymentMethod: 'tunai',
    referenceNo: 'KW-FASUM-0908',
    status: 'active',
    notes: 'Bahan bakar mesin pemotong rumput dan perlengkapan',
    createdAt: '2026-09-08T09:00:00.000Z',
    createdBy: 'bendahara_demo',
  },
];

export const INITIAL_DOCUMENTATION: DocumentationItem[] = [
  {
    id: 'doc-1',
    title: '[Demo Foto 01] Dokumentasi Suasana Lingkungan Kompleks Perumahan (Contoh)',
    date: 'September 2026',
    category: 'lingkungan',
    description:
      '(Foto Contoh) Ilustrasi keasrian kawasan hunian bernuansa pegunungan sejuk untuk keperluan demonstrasi galeri portal warga.',
    image: heroImage,
    photographer: 'Dokumentasi Warga [Demo]',
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'doc-2',
    title: '[Demo Foto 02] Dokumentasi Gotong Royong Kebersihan Warga (Contoh)',
    date: 'Agustus 2026',
    category: 'kerja-bakti',
    description:
      '(Foto Contoh) Ilustrasi kegiatan kebersamaan warga dalam membersihkan area bersama dan menjaga lingkungan tetap bersih.',
    image: cleanupImage,
    photographer: 'Seksi Humas [Demo]',
    createdAt: '2026-08-20T08:00:00.000Z',
  },
  {
    id: 'doc-3',
    title: '[Demo Foto 03] Dokumentasi Area Fasilitas Bersama & Taman (Contoh)',
    date: 'September 2026',
    category: 'pembangunan',
    description:
      '(Foto Contoh) Ilustrasi ruang terbuka hijau dan gazebo peristirahatan warga sebagai sarana interaksi sosial yang nyaman.',
    image: gardenImage,
    photographer: 'Bpk. Contoh 01',
    createdAt: '2026-09-05T09:00:00.000Z',
  },
];

export const RONDA_SCHEDULES: RondaSchedule[] = [
  {
    day: 'Senin',
    team: 'Regu Contoh 1 [Demo]',
    coordinator: 'Bpk. Contoh 01',
    houses: ['Contoh H-01', 'Contoh H-02', 'Contoh H-03', 'Contoh H-04', 'Contoh H-05'],
  },
  {
    day: 'Selasa',
    team: 'Regu Contoh 2 [Demo]',
    coordinator: 'Bpk. Contoh 02',
    houses: ['Contoh H-06', 'Contoh H-07', 'Contoh H-08', 'Contoh H-09', 'Contoh H-10'],
  },
  {
    day: 'Rabu',
    team: 'Regu Contoh 3 [Demo]',
    coordinator: 'Bpk. Contoh 03',
    houses: ['Contoh H-11', 'Contoh H-12', 'Contoh H-13', 'Contoh H-14', 'Contoh H-15'],
  },
  {
    day: 'Kamis',
    team: 'Regu Contoh 4 [Demo]',
    coordinator: 'Bpk. Contoh 04',
    houses: ['Contoh H-16', 'Contoh H-17', 'Contoh H-18', 'Contoh H-19', 'Contoh H-20'],
  },
  {
    day: 'Jumat',
    team: 'Regu Contoh 5 [Demo]',
    coordinator: 'Bpk. Contoh 05',
    houses: ['Contoh H-21', 'Contoh H-22', 'Contoh H-23', 'Contoh H-24', 'Contoh H-25'],
  },
  {
    day: 'Sabtu',
    team: 'Regu Contoh 6 [Demo]',
    coordinator: 'Bpk. Contoh 06',
    houses: ['Contoh H-26', 'Contoh H-27', 'Contoh H-28', 'Contoh H-29', 'Contoh H-30'],
  },
  {
    day: 'Minggu',
    team: 'Regu Contoh 7 [Demo]',
    coordinator: 'Bpk. Contoh 07',
    houses: ['Contoh H-31', 'Contoh H-32', 'Contoh H-33', 'Contoh H-34', 'Contoh H-35'],
  },
];

export const INITIAL_REPORTS: CitizenReport[] = [
  {
    id: 'rep-1',
    date: '2026-09-23',
    residentName: 'Ibu Contoh 01',
    houseNumber: 'H-XX (Contoh)',
    phone: '08xxxxxxxxxx',
    category: 'fasilitas',
    title: '[Contoh Laporan] Lampu Penerangan Jalan Perlu Pengecekan',
    description:
      '(Contoh Laporan Warga) Lampu penerangan jalan di tiang depan rumah berkedip saat malam hari. Mohon bantuan teknisi sarpras untuk melakukan pengecekan.',
    status: 'diproses',
    createdAt: '2026-09-23T15:20:00.000Z',
  },
  {
    id: 'rep-2',
    date: '2026-09-19',
    residentName: 'Bpk. Contoh 02',
    houseNumber: 'H-YY (Contoh)',
    phone: '08xxxxxxxxxx',
    category: 'kebersihan',
    title: '[Contoh Laporan] Pembersihan Ranting di Saluran Air',
    description:
      '(Contoh Laporan Warga) Daun kering dan ranting menumpuk di saluran air, mohon dapat diagendakan saat kerja bakti bersama.',
    status: 'selesai',
    createdAt: '2026-09-19T08:10:00.000Z',
  },
];

/**
 * MOCK DATA UNIT RUMAH WARGA (HOUSEHOLDS) - DATA DEMO
 * Digunakan untuk pemetaan iuran IPL dan pelaporan administrasi warga.
 */
export const INITIAL_HOUSEHOLDS: Household[] = [
  {
    id: 'hh-01',
    houseNumber: 'H-01',
    residentName: 'Bpk. Hendra Wijaya [Demo]',
    occupancyStatus: 'huni',
    isActive: true,
    familyMembers: 4,
    notes: 'Unit aktif utama',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'hh-02',
    houseNumber: 'H-02',
    residentName: 'Ibu Ratna Dewi [Demo]',
    occupancyStatus: 'huni',
    isActive: true,
    familyMembers: 3,
    notes: 'Keluarga inti',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'hh-03',
    houseNumber: 'H-03',
    residentName: 'Bpk. Ahmad Fauzi [Demo]',
    occupancyStatus: 'huni',
    isActive: true,
    familyMembers: 5,
    notes: 'Koordinator RT',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'hh-04',
    houseNumber: 'H-04',
    residentName: 'Bpk. Agus Santoso [Demo]',
    occupancyStatus: 'semi-huni',
    isActive: true,
    familyMembers: 2,
    notes: 'Tinggal akhir pekan',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'hh-05',
    houseNumber: 'H-05',
    residentName: 'Ibu Siti Aminah [Demo]',
    occupancyStatus: 'huni',
    isActive: true,
    familyMembers: 3,
    notes: 'Anggota paguyuban',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'hh-06',
    houseNumber: 'H-06',
    residentName: 'Bpk. Budi Pratama [Demo]',
    occupancyStatus: 'huni',
    isActive: true,
    familyMembers: 4,
    notes: 'Pengurus humas',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'hh-07',
    houseNumber: 'H-07',
    residentName: 'Keluarga Pratama [Demo]',
    occupancyStatus: 'kosong',
    isActive: false,
    familyMembers: 0,
    notes: 'Rumah dalam proses renovasi / belum dihuni',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'hh-08',
    houseNumber: 'H-08',
    residentName: 'Bpk. Dedi Supriyadi [Demo]',
    occupancyStatus: 'huni',
    isActive: true,
    familyMembers: 3,
    notes: 'Warga Blok H',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
];

/**
 * MOCK DATA PEMBAYARAN IPL (IURAN PENGELOLAAN LINGKUNGAN) - DATA DEMO
 * Periode berjalan: 2026-09
 * Standar tarif iuran per rumah: Rp50.000
 */
export const INITIAL_IPL_PAYMENTS: IPLPayment[] = [
  {
    id: 'ipl-202609-01',
    householdId: 'hh-01',
    houseNumber: 'H-01',
    residentName: 'Bpk. Hendra Wijaya [Demo]',
    period: '2026-09',
    amount: 50000,
    paidAmount: 50000,
    status: 'lunas',
    paidAt: '2026-09-05T09:00:00.000Z',
    transactionId: 'tx-ipl-01',
    notes: 'Lunas transfer bank',
    createdAt: '2026-09-05T09:00:00.000Z',
  },
  {
    id: 'ipl-202609-02',
    householdId: 'hh-02',
    houseNumber: 'H-02',
    residentName: 'Ibu Ratna Dewi [Demo]',
    period: '2026-09',
    amount: 50000,
    paidAmount: 50000,
    status: 'lunas',
    paidAt: '2026-09-06T14:30:00.000Z',
    transactionId: 'tx-ipl-02',
    notes: 'Lunas via bendahara',
    createdAt: '2026-09-06T14:30:00.000Z',
  },
  {
    id: 'ipl-202609-03',
    householdId: 'hh-03',
    houseNumber: 'H-03',
    residentName: 'Bpk. Ahmad Fauzi [Demo]',
    period: '2026-09',
    amount: 50000,
    paidAmount: 25000,
    status: 'sebagian',
    paidAt: '2026-09-10T10:00:00.000Z',
    transactionId: 'tx-ipl-03',
    notes: 'Pembayaran termin pertama Rp25.000',
    createdAt: '2026-09-10T10:00:00.000Z',
  },
  {
    id: 'ipl-202609-04',
    householdId: 'hh-04',
    houseNumber: 'H-04',
    residentName: 'Bpk. Agus Santoso [Demo]',
    period: '2026-09',
    amount: 50000,
    paidAmount: 50000,
    status: 'lunas',
    paidAt: '2026-09-12T08:15:00.000Z',
    transactionId: 'tx-ipl-04',
    notes: 'Lunas transfer',
    createdAt: '2026-09-12T08:15:00.000Z',
  },
  {
    id: 'ipl-202609-05',
    householdId: 'hh-05',
    houseNumber: 'H-05',
    residentName: 'Ibu Siti Aminah [Demo]',
    period: '2026-09',
    amount: 50000,
    paidAmount: 0,
    status: 'belum',
    notes: 'Menunggu konfirmasi pembayaran',
    createdAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'ipl-202609-06',
    householdId: 'hh-06',
    houseNumber: 'H-06',
    residentName: 'Bpk. Budi Pratama [Demo]',
    period: '2026-09',
    amount: 50000,
    paidAmount: 50000,
    status: 'lunas',
    paidAt: '2026-09-15T11:00:00.000Z',
    transactionId: 'tx-ipl-05',
    notes: 'Lunas tunai',
    createdAt: '2026-09-15T11:00:00.000Z',
  },
  {
    id: 'ipl-202609-08',
    householdId: 'hh-08',
    houseNumber: 'H-08',
    residentName: 'Bpk. Dedi Supriyadi [Demo]',
    period: '2026-09',
    amount: 50000,
    paidAmount: 0,
    status: 'belum',
    notes: 'Belum melakukan konfirmasi',
    createdAt: '2026-09-01T00:00:00.000Z',
  },
];
